// ============================================================
// Data Governance Page
// ============================================================

import { useDemoContext } from '../context/DemoContext';
import { EmptyState } from '../components/StateComponents';
import { Database, ShieldCheck, AlertCircle, Lock } from 'lucide-react';

// Frontend-level sensitive key filter (defense-in-depth)
const SENSITIVE_KEYS = new Set([
  'private_parameters', 'raw_seed', 'seed', 'seed_hash',
  'secret', 'private_key', 'api_key', 'openai_api_key', 'model_weights',
]);

function isSensitiveKey(key: string): boolean {
  return SENSITIVE_KEYS.has(key.toLowerCase());
}

export default function GovernancePage() {
  const { data } = useDemoContext();

  if (!data) return <div style={{ padding: '28px' }}><EmptyState message="Run the canonical demo to view data governance information." /></div>;

  const gov = data.data_governance;

  return (
    <div className="fade-in" style={{ padding: '28px', maxWidth: '900px' }}>
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '20px', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Database size={20} color="#3b82f6" />
          Data Governance
        </h1>
        <p style={{ color: '#94a3b8', fontSize: '13px', marginTop: '4px' }}>
          Sanitized data governance schedule and privacy protection information.
        </p>
      </div>

      <div className="alert alert-info" style={{ marginBottom: '20px' }}>
        <ShieldCheck size={14} />
        <span>
          All sensitive fields (private parameters, seeds, secrets, API keys, model weights) are excluded from API output
          and additionally filtered by frontend sanitization. This page shows only public governance metadata.
        </span>
      </div>

      {/* Governance schedule */}
      {gov && (
        <div className="card" style={{ marginBottom: '20px' }}>
          <div className="card-header">
            <span style={{ fontWeight: 600 }}>Governance Schedule</span>
          </div>
          {Object.entries(gov)
            .filter(([k]) => !isSensitiveKey(k))
            .map(([k, v]) => (
              <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid #1e293b', gap: '12px' }}>
                <span style={{ fontSize: '12px', color: '#94a3b8', textTransform: 'capitalize', flexShrink: 0 }}>
                  {k.replace(/_/g, ' ')}
                </span>
                <span style={{ fontSize: '13px', color: '#e2e8f0', textAlign: 'right', wordBreak: 'break-word' }}>
                  {String(v ?? '—')}
                </span>
              </div>
            ))}
        </div>
      )}

      {/* Evidence provenance */}
      <div className="card" style={{ marginBottom: '20px' }}>
        <div className="card-header">
          <span style={{ fontWeight: 600 }}>Evidence Provenance</span>
        </div>
        <div className="alert alert-info" style={{ marginBottom: '12px' }}>
          <AlertCircle size={13} />
          <span>Evidence levels distinguish between independently validated measurements and government-declared parameters.</span>
        </div>
        {[
          { level: 'INDEPENDENTLY_VALIDATED', desc: 'Generated by independent black-box evaluation with cryptographic artifact integrity and self-verifying evaluator.' },
          { level: 'OBSERVED', desc: 'Field-measured parameter from government sensor data or field logs.' },
          { level: 'DECLARED', desc: 'Government-declared parameter from official survey or inventory.' },
          { level: 'ESTIMATED', desc: 'Estimated parameter from field analyst judgment or proxy data.' },
          { level: 'UNVERIFIED', desc: 'Unverified field estimate — carries lowest evidentiary weight.' },
        ].map(({ level, desc }) => (
          <div key={level} style={{ padding: '10px 0', borderBottom: '1px solid #1e293b' }}>
            <div style={{ fontWeight: 600, fontSize: '12px', color: '#93c5fd', marginBottom: '4px' }}>{level}</div>
            <div style={{ fontSize: '12px', color: '#64748b' }}>{desc}</div>
          </div>
        ))}
      </div>

      {/* Privacy protection */}
      <div className="card" style={{ marginBottom: '20px' }}>
        <div className="card-header">
          <span style={{ fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Lock size={15} />
            Privacy & Security Boundaries
          </span>
        </div>
        {[
          { label: 'Private Test Seeds', value: 'Never exposed in API output or UI. Backend enforces exclusion.' },
          { label: 'Private Parameters', value: 'Excluded from all API responses. Frontend additionally filters.' },
          { label: 'Model Weights', value: 'Never transmitted. Vendor artifacts evaluated as black-box.' },
          { label: 'API Keys / Secrets', value: 'Never stored in frontend code or transmitted to browser.' },
          { label: 'Citizen Data', value: `Owner: ${gov?.citizen_data_owner ?? 'Government Department'} · Deleted after ${gov?.retention_days ?? 365} days.` },
        ].map(({ label, value }) => (
          <div key={label} style={{ display: 'grid', gridTemplateColumns: '220px 1fr', gap: '12px', padding: '10px 0', borderBottom: '1px solid #1e293b' }}>
            <span style={{ fontSize: '12px', color: '#94a3b8', fontWeight: 500 }}>{label}</span>
            <span style={{ fontSize: '12px', color: '#64748b' }}>{value}</span>
          </div>
        ))}
      </div>

      {/* Auditability */}
      <div className="card">
        <div className="card-header">
          <span style={{ fontWeight: 600 }}>Auditability Guarantees</span>
        </div>
        {[
          'Outcome Contract locked and hashed before vendor evaluation begins.',
          'Test suite hash published — results are reproducible given the same seed.',
          'All vendor artifacts frozen via SHA-256 before evaluation.',
          'Evidence records carry cryptographic bindings and expiry windows.',
          'Human authorization decisions recorded with actor ID and justification.',
          'Audit trail is append-only and cannot be modified post-hoc.',
          'AI diagnostics are clearly labeled advisory and cannot alter governance state.',
        ].map((g, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', padding: '8px 0', borderBottom: '1px solid #1e293b' }}>
            <ShieldCheck size={13} color="#16a34a" style={{ flexShrink: 0, marginTop: '2px' }} aria-hidden="true" />
            <span style={{ fontSize: '12px', color: '#94a3b8' }}>{g}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
